algoritmos-rw/algo2_sistema_entregas

templates/index.html

Tiene un `:` como si fuese a llenarse con algo pero es nada mas informativo.

Typo en mensaje de ayuda

---

templates/index.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/algoritmos-rw/algo2_sistema_entregas/28)

Simplificación del código tras aceptar ahora un solo archivo

---

config-sample.py
main.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/algoritmos-rw/algo2_sistema_entregas/32)

Habilitar entrega de parcialitos (y que no se envien a un corrector)

---

planilla.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/algoritmos-rw/algo2_sistema_entregas/33)

Headers de DatosDocentes vuelven/volerán a estar en la fila 1

---

main.py
templates/index.html
templates/result.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/algoritmos-rw/algo2_sistema_entregas/34)

Simplificaciones de sintaxis y mejor manejo de errores

---

main.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/algoritmos-rw/algo2_sistema_entregas/40)

Fix parcialitos

---

algorw/corrector/ai_corrector.py
algorw/corrector/alu_repos.py
algorw/corrector/corrector.py

Se importa el código del corrector para tener alu_repos, y empezar a usar la cola
de trabajo de Redis.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/algoritmos-rw/algo2_sistema_entregas/43)

Subtree merge del corrector

---

.flake8
algorw/models.py
algorw/planilla.py
algorw/sheets.py
main.py
planilla.py
pyproject.toml
requirements.in
requirements.txt

Módulos introducidos:
- algorw/models.py: clases Alumne y Docente; clase base Model con
código para convertir de columnas de Google Sheets a BaseModel.
- algorw/sheets.py: clase/mixin para obtener varias hojas de una
planilla a la vez, directamente con la API de Google Sheets.
- algorw/planila.py: clase Planilla que parsea Notas, DatosAlumnos
y DatosDocentes. Proporciona un método get_alulist() para obtener
alumnes a partir de legajo, o grupo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/algoritmos-rw/algo2_sistema_entregas/36)

Nueva planilla con tipos y validación de datos

---

algorw/corrector/corrector.py
algorw/utils.py
entregas.yml
main.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/algoritmos-rw/algo2_sistema_entregas/45)

Deduplicar sendmail() de entregas y corrector

---

scripts/source2pdf.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/algoritmos-rw/algo2_sistema_entregas/47)

Script para generacion de pdfs de parcialito (incluyendo imagenes)

---

algorw/models.py
algorw/planilla.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/algoritmos-rw/algo2_sistema_entregas/52)

Usar safeidx() en _parse_notas, para cuando la planilla está vacía

---

algorw/common/models.py
algorw/common/tasks.py
algorw/corrector/alu_repos.py
algorw/corrector/corrector.py
main.py

Estos son los cambios requeridos en el "backend" (corrector.py), lo
siguiente es que el frontend (main.py) complete el campo alu_repo de
la tarea CorregirTask—leyendo para ello la planilla, y las guidelines
de #49.
Como seguramente haga merge de este PR una vez a la par que el PR del
front-end, voy a decir que this closes: #51.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/algoritmos-rw/algo2_sistema_entregas/53)

Incluir en CorrectorTask el alu_repo a donde sincronizar la entrega

---

algorw/planilla.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/algoritmos-rw/algo2_sistema_entregas/56)

Acceder a Nro Grupo con safeidx()

---

algorw/models.py
algorw/planilla.py
main.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/algoritmos-rw/algo2_sistema_entregas/55)

Leer la hoja Repos para informar al corrector qué repo sincronizar

---

algorw/corrector/alu_repos.py
algorw/corrector/corrector.py
requirements.txt

Also:
- actualizar PyGithub de 1.51 a 1.53 para los typing hints de
delete_branch_on_merge (PyGithub/PyGithub#1639, incompleta)
- eliminar ramas de except KeyError/ValueError que ya no aplican
tras el último refactor a alu_repos.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/algoritmos-rw/algo2_sistema_entregas/57)

alu_repos: en los repos creados, dar role "admin" al equipo docente

---

algorw/planilla.py

Closes: #63.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/algoritmos-rw/algo2_sistema_entregas/64)

Solo reconocer legajos que aparezcan en la hoja Notas

---

.gitignore
.secrets.template
algorw/common/tasks.py
algorw/corrector/alu_repos.py
algorw/corrector/corrector.py
config.py
entregas.yml
main.py
requirements.in
requirements.txt

Estos aparecen en la interfaz y en las pull requests al lado de cada commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/algoritmos-rw/algo2_sistema_entregas/65)

Crear checkruns de Github con la salida del corrector

---

main.py
templates/base.html
templates/index.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/algoritmos-rw/algo2_sistema_entregas/70)

Eliminar captcha para entregas

---

scripts/entregadores_top.py

Para Nacho, con amor
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/algoritmos-rw/algo2_sistema_entregas/72)

Script para obtener top de entregadores de un cuatrimestre

---

.mypy.ini
algorw/common/tasks.py
algorw/corrector/alu_repos.py
algorw/corrector/corrector.py
algorw/models.py
algorw/planilla.py
algorw/sheets.py
main.py
requirements.dev.in
requirements.dev.txt

- 594e9e2a08c22c28504d84647aae0f8e572575c4 Give a type hint for Moss._emoji instead of ignoring the error
- b2426e9866e794fae6665cdf41c664685f899156 Upgrade mypy to 0.971
- d1261bb5126076c09dbf59d0629128340133e46e Activate --no-implicit-optional in mypy
- 137fe6079fe8eddb443403ff4af195286695a2b8 Activate --warn-return-any in mypy
- e14a350fbceab1d31aee82af524e1e8dcb87ece4 Activate --disallow-incomplete-defs in mypy
- 68f5c4653066c2eb88a3100479e052eb595dd499 Make RepoSync.auth_token a plain string, not SecretStr
- dcccbc853f259b4b4c666f6310d5aeccf8036796 Fix remaining typecheck issues and enable --check-untyped-defs
- 6c2140a6fe091b9b5254eb7ebc45febae4cab379 Simplify mypy configuration, rewriting it in terms of --strict
-----

Upgrade mypy and fix remaining issues
